version: "3"
services:
  db:
    image: postgis/postgis
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_data:/data
  web:
    build: ./
    command: bin/rails server -p 3000 -b 0.0.0.0
    env_file: ./.env
    volumes:
      - ./:/app
      - bundle_data:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  sidekiq:
    build: ./
    command: "bundle exec sidekiq"
    env_file: ./.env
    volumes:
      - ./:/app
      - bundle_data:/bundle
    depends_on:
      - db
      - redis
  ngrok:
    image: wernight/ngrok
    command: "ngrok http -authtoken ${NGROK_AUTH_TOKEN} -hostname ${NGROK_HOST} web:3000"
    depends_on:
      - web
volumes:
  bundle_data:
  postgres_data:
  redis_data:
