version: "3"
services:
  app:
    build: ./
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec foreman start -f Procfile.dev"
    env_file: ./.env
    volumes:
      - ./:/app/:rw,delegated
      - bundle_data:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  db:
    image: postgis/postgis:13-3.3
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2
    volumes:
      - redis_data:/data
volumes:
  bundle_data:
  postgres_data:
  redis_data:
