send_alerts:
  cron: "0 10 * * * America/Chicago"
  class: "SendAlertsJob"

sync_cdot_permits:
  cron: "0 4 * * * America/Chicago"
  class: "SyncCdotPermitsJob"

cleanup_stale_cdot_permits:
  cron: "0 5 * * * America/Chicago"
  class: "CleanupStaleCdotPermitsJob"

backfill_permit_segment_geocoding:
  cron: "30 5 * * * America/Chicago"
  class: "BackfillPermitSegmentGeocodingJob"

send_permit_alerts:
  cron: "20 11 * * * America/Chicago"
  class: "SendPermitAlertsJob"
