name: CI

on:
  pull_request:
    types: [opened, synchronize]

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: demo4u!

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_PASSWORD: demo4u!
      DB_HOST: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0

      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.10
          bundle install --jobs 4 --retry 3

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          while ! pg_isready -h postgres -p 5432 -U postgres; do
            sleep 1
          done

      - name: Setup database
        run: |
          RAILS_ENV=test bundle exec rails db:create db:schema:load

      - name: Run tests
        run: |
          RAILS_ENV=test bundle exec rails test
